<?php
/*
 * Copyright 2017 Sterling Talent Solutions
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * AddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kennect-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-10-26T14:02:28.460-07:00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AddressTest Class Doc Comment
 *
 * @category    Class */
// * @description Address
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AddressTest extends \PHPUnit_Framework_TestCase
{
    private static $address;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
        $data = array(
            'address_line' => 'addressLine',
            'country_code' => 'countryCode',
            'municipality' => 'municipality',
            'postal_code' => 'postalCode',
            'region_code' => 'regionCode'
        );
        self::$address = new Model\Address($data);
    }

    /**
     * Test "Address"
     */
    public function testAddress()
    {
        $expectedJson = '{
            "addressLine": "addressLine",
            "countryCode": "countryCode",
            "municipality": "municipality",
            "postalCode": "postalCode",
            "regionCode": "regionCode"
        }';
        $this->assertJsonStringEqualsJsonString($expectedJson, self::$address->__toString());
    }

    /**
     * Test attribute "address_line"
     */
    public function testPropertyAddressLine()
    {
        $this->assertEquals("addressLine", self::$address->getAddressLine());
    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {
        $this->assertEquals("countryCode", self::$address->getCountryCode());
    }

    /**
     * Test attribute "municipality"
     */
    public function testPropertyMunicipality()
    {
        $this->assertEquals("municipality", self::$address->getMunicipality());
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
        $this->assertEquals("postalCode", self::$address->getPostalCode());
    }

    /**
     * Test attribute "region_code"
     */
    public function testPropertyRegionCode()
    {
        $this->assertEquals("regionCode", self::$address->getRegionCode());
    }
}
