<?php
/*
 * Copyright 2017 Sterling Talent Solutions
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * DriversLicenseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kennect-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-10-26T14:02:28.460-07:00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DriversLicenseTest Class Doc Comment
 *
 * @category    Class */
// * @description DriversLicense
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DriversLicenseTest extends \PHPUnit_Framework_TestCase
{
    private static $subject;
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
        $data = array(
            'issuing_agency' => 'issuing_agency',
            'license_number' => 'license_number',
            'type' => 'type'
        );

        self::$subject = new Model\DriversLicense($data);
    }
    /**
     * Test "DriversLicense"
     */
    public function testDriversLicense()
    {

        $expectedJson = '{
            "issuingAgency": "issuing_agency",
            "licenseNumber": "license_number",
            "type": "type"
        }';
        $this->assertJsonStringEqualsJsonString($expectedJson, self::$subject->__toString());
    }

    /**
     * Test attribute "issuing_agency"
     */
    public function testPropertyIssuingAgency()
    {
        $this->assertEquals("issuing_agency", self::$subject->getIssuingAgency());
    }

    /**
     * Test attribute "license_number"
     */
    public function testPropertyLicenseNumber()
    {
        $this->assertEquals("license_number", self::$subject->getLicenseNumber());
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        $this->assertEquals("type", self::$subject->getType());
    }
}
