<?php
/*
 * Copyright 2017 Sterling Talent Solutions
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * PackageResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kennect-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-10-26T14:02:28.460-07:00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PackageResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description PackageResponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PackageResponseTest extends \PHPUnit_Framework_TestCase
{
    private static $subject;
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
        $data = array(
            'active' => true,
            'components' => array('components'),
            'id' => 'id',
            'required_fields' => array('required_fields'),
            'supported' => true,
            'title' => 'title'
        );

        self::$subject = new Model\PackageResponse($data);
    }

    /**
     * Test "PackageResponse"
     */
    public function testPackageResponse()
    {
        $expectedJson = '{
            "active": true,
            "components": [
                "components"
            ],
            "id": "id",
            "requiredFields": [
                "required_fields"
            ],
            "supported": true,
            "title": "title"
        }';
        $this->assertJsonStringEqualsJsonString($expectedJson, self::$subject->__toString());
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
        $this->assertEquals(true, self::$subject->getActive());
    }

    /**
     * Test attribute "components"
     */
    public function testPropertyComponents()
    {
        $this->assertEquals("components", self::$subject->getComponents()[0]);
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $this->assertEquals("id", self::$subject->getId());
    }

    /**
     * Test attribute "required_fields"
     */
    public function testPropertyRequiredFields()
    {
        $this->assertEquals("required_fields", self::$subject->getRequiredFields()[0]);
    }

    /**
     * Test attribute "supported"
     */
    public function testPropertySupported()
    {
        $this->assertEquals(true, self::$subject->getSupported());
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
        $this->assertEquals("title", self::$subject->getTitle());
    }
}
