<?php
/*
 * Copyright 2017 Sterling Talent Solutions
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * ScheduleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Oda\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kennect-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-10-26T14:02:28.460-07:00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Oda\Client;

/**
 * ScheduleTest Class Doc Comment
 *
 * @category    Class */
// * @description Schedule
/**
 * @package     Oda\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScheduleTest extends \PHPUnit_Framework_TestCase
{
    private static $subject;
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
        date_default_timezone_set('UTC');
        $data = array(
            'end_at' => (new \DateTime())->setTimestamp(0),
            'interval' => new Model\Interval(),
            'start_at' => (new \DateTime())->setTimestamp(0)
        );

        self::$subject = new Model\Schedule($data);
    }

    /**
     * Test "Schedule"
     */
    public function testSchedule()
    {

        $expectedJson = '{
            "endAt": "1970-01-01T00:00:00+00:00",
            "interval": {},
            "startAt": "1970-01-01T00:00:00+00:00"
        }';
        $this->assertJsonStringEqualsJsonString($expectedJson, self::$subject->__toString());
    }

    /**
     * Test attribute "end_at"
     */
    public function testPropertyEndAt()
    {
        $this->assertEquals(0, self::$subject->getEndAt()->getTimestamp());
    }

    /**
     * Test attribute "interval"
     */
    public function testPropertyInterval()
    {
        $this->assertEquals("Oda\Client\Model\Interval", get_class(self::$subject->getInterval()));
    }

    /**
     * Test attribute "start_at"
     */
    public function testPropertyStartAt()
    {
        $this->assertEquals(0, self::$subject->getEndAt()->getTimestamp());
    }
}
