<?php
/*
 * Copyright 2017 Sterling Talent Solutions
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * ScreeningResponseReportItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Oda\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kennect-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-10-26T14:02:28.460-07:00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Oda\Client;

/**
 * ScreeningResponseReportItemTest Class Doc Comment
 *
 * @category    Class */
// * @description ScreeningResponseReportItem
/**
 * @package     Oda\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScreeningResponseReportItemTest extends \PHPUnit_Framework_TestCase
{
    private static $subject;
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
        $data = array(
            'question_id' => 'question_id',
            'response' => 'response'
        );

        self::$subject = new Model\Answer($data);
    }
    /**
     * Test "ScreeningResponseReportItem"
     */
    public function testScreeningResponseReportItem()
    {
        $expectedJson = '{
            "questionId": "question_id",
            "response": "response"
        }';
        $this->assertJsonStringEqualsJsonString($expectedJson, self::$subject->__toString());
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $this->assertEquals("response", self::$subject->getResponse());
    }

    /**
     * Test attribute "result"
     */
    public function testPropertyResult()
    {
        $this->assertEquals("response", self::$subject->getResponse());
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        $this->assertEquals("response", self::$subject->getResponse());
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        $this->assertEquals("response", self::$subject->getResponse());
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
        $this->assertEquals("response", self::$subject->getResponse());
    }
}
