<?php
/*
 * Copyright 2017 Sterling Talent Solutions
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * ScreeningResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Oda\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kennect-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-10-26T14:02:28.460-07:00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Oda\Client;

/**
 * ScreeningResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description ScreeningResponse
/**
 * @package     Oda\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScreeningResponseTest extends \PHPUnit_Framework_TestCase
{
    private static $subject;
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
        date_default_timezone_set('UTC');
        $data = array(
            'adverse_actions' => array(new Model\AdverseActionResponse()),
            'billing_code' => 'billing_code',
            'callback' => new Model\CallbackResponse(),
            'candidate_id' => 'candidate_id',
            'client_criteria_result' => 'client_criteria_result',
            'dispute' => new Model\Dispute(),
            'id' => 'id',
            'invite' => new Model\Invite(),
            'links' => new Model\ScreeningResponseLink(),
            'package_id' => 'package_id',
            'reference_codes' => array(new Model\ReferenceCode()),
            'report_items' => array(new Model\ScreeningResponseReportItem()),
            'result' => 'result',
            'status' => 'status',
            'submitted_at' => (new \DateTime())->setTimestamp(0),
            'trusted_user_id' => 'trusted_user_id',
            'updated_at' => (new \DateTime())->setTimestamp(0)
        );


        self::$subject = new Model\ScreeningResponse($data);
    }
    /**
     * Test "ScreeningResponse"
     */
    public function testScreeningResponse()
    {
        $expectedJson = '{
            "adverseActions": [
                {}
            ],
            "billingCode": "billing_code",
            "callback": {},
            "candidateId": "candidate_id",
            "clientCriteriaResult": "client_criteria_result",
            "dispute": {},
            "id": "id",
            "invite": {},
            "links": {},
            "packageId": "package_id",
            "referenceCodes": [
                {}
            ],
            "reportItems": [
                {}
            ],
            "result": "result",
            "status": "status",
            "submittedAt": "1970-01-01T00:00:00+00:00",
            "trustedUserId": "trusted_user_id",
            "updatedAt": "1970-01-01T00:00:00+00:00"
        }';
        $this->assertJsonStringEqualsJsonString($expectedJson, self::$subject->__toString());
    }

    /**
     * Test attribute "adverse_actions"
     */
    public function testPropertyAdverseActions()
    {
        $this->assertEquals("Oda\Client\Model\AdverseActionResponse", get_class(self::$subject->getAdverseActions()[0]));
    }

    /**
     * Test attribute "billing_code"
     */
    public function testPropertyBillingCode()
    {
        $this->assertEquals("billing_code", self::$subject->getBillingCode());
    }

    /**
     * Test attribute "callback"
     */
    public function testPropertyCallback()
    {
        $this->assertEquals("Oda\Client\Model\CallbackResponse", get_class(self::$subject->getCallback()));
    }

    /**
     * Test attribute "candidate_id"
     */
    public function testPropertyCandidateId()
    {
        $this->assertEquals("candidate_id", self::$subject->getCandidateId());
    }

    /**
     * Test attribute "client_criteria_result"
     */
    public function testPropertyClientCriteriaResult()
    {
        $this->assertEquals("client_criteria_result", self::$subject->getClientCriteriaResult());
    }

    /**
     * Test attribute "dispute"
     */
    public function testPropertyDispute()
    {
        $this->assertEquals("Oda\Client\Model\Dispute", get_class(self::$subject->getDispute()));
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $this->assertEquals("id", self::$subject->getId());
    }

    /**
     * Test attribute "invite"
     */
    public function testPropertyInvite()
    {
        $this->assertEquals("Oda\Client\Model\Invite", get_class(self::$subject->getInvite()));
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
        $this->assertEquals("Oda\Client\Model\ScreeningResponseLink", get_class(self::$subject->getLinks()));
    }

    /**
     * Test attribute "package_id"
     */
    public function testPropertyPackageId()
    {
        $this->assertEquals("package_id", self::$subject->getPackageId());
    }

    /**
     * Test attribute "reference_codes"
     */
    public function testPropertyReferenceCodes()
    {
        $this->assertEquals("Oda\Client\Model\ReferenceCode", get_class(self::$subject->getReferenceCodes()[0]));
    }

    /**
     * Test attribute "report_items"
     */
    public function testPropertyReportItems()
    {
        $this->assertEquals("Oda\Client\Model\ScreeningResponseReportItem", get_class(self::$subject->getReportItems()[0]));
    }

    /**
     * Test attribute "result"
     */
    public function testPropertyResult()
    {
        $this->assertEquals("result", self::$subject->getResult());
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        $this->assertEquals("status", self::$subject->getStatus());
    }

    /**
     * Test attribute "submitted_at"
     */
    public function testPropertySubmittedAt()
    {
        $this->assertEquals(0, self::$subject->getSubmittedAt()->getTimestamp());
    }

    /**
     * Test attribute "trusted_user_id"
     */
    public function testPropertyTrustedUserId()
    {
        $this->assertEquals("trusted_user_id", self::$subject->getTrustedUserId());
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
        $this->assertEquals(0, self::$subject->getUpdatedAt()->getTimestamp());
    }
}
