<?php
/*
 * Copyright 2017 Sterling Talent Solutions
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * SubscriptionResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Oda\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kennect-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-10-26T14:02:28.460-07:00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Oda\Client;

/**
 * SubscriptionResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description SubscriptionResponse
/**
 * @package     Oda\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionResponseTest extends \PHPUnit_Framework_TestCase
{
    private static $subject;
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
        date_default_timezone_set('UTC');
        $data = array(
            'created_at' => (new \DateTime())->setTimestamp(0),
            'id' => 'id',
            'metrics' => new Model\Metrics(),
            'next_run_at' => (new \DateTime())->setTimestamp(0),
            'schedule' => new Model\Schedule(),
            'screening' => new Model\ScreeningRequest(),
            'status' => 'status',
            'updated_at' => (new \DateTime())->setTimestamp(0)
        );

        self::$subject = new Model\SubscriptionResponse($data);
    }
    /**
     * Test "SubscriptionResponse"
     */
    public function testSubscriptionResponse()
    {

        $expectedJson = '{
            "createdAt": "1970-01-01T00:00:00+00:00",
            "id": "id",
            "metrics": {},
            "nextRunAt": "1970-01-01T00:00:00+00:00",
            "schedule": {},
            "screening": {},
            "status": "status",
            "updatedAt": "1970-01-01T00:00:00+00:00"
        }';
        $this->assertJsonStringEqualsJsonString($expectedJson, self::$subject->__toString());
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
        $this->assertEquals(0, self::$subject->getCreatedAt()->getTimestamp());
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $this->assertEquals("id", self::$subject->getId());
    }

    /**
     * Test attribute "metrics"
     */
    public function testPropertyMetrics()
    {
        $this->assertEquals("Oda\Client\Model\Metrics", get_class(self::$subject->getMetrics()));
    }

    /**
     * Test attribute "next_run_at"
     */
    public function testPropertyNextRunAt()
    {
        $this->assertEquals(0, self::$subject->getNextRunAt()->getTimestamp());
    }

    /**
     * Test attribute "schedule"
     */
    public function testPropertySchedule()
    {
        $this->assertEquals("Oda\Client\Model\Schedule", get_class(self::$subject->getSchedule()));
    }

    /**
     * Test attribute "screening"
     */
    public function testPropertyScreening()
    {
        $this->assertEquals("Oda\Client\Model\ScreeningRequest", get_class(self::$subject->getScreening()));
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        $this->assertEquals("status", self::$subject->getStatus());
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
        $this->assertEquals(0, self::$subject->getUpdatedAt()->getTimestamp());
    }
}
