<?php
/*
 * Copyright 2017 Sterling Talent Solutions
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Oda\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kennect-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-10-26T14:02:28.460-07:00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Oda\Client;

use \Oda\Client\Configuration;
use \Oda\Client\ApiClient;
use \Oda\Client\ApiException;
use \Oda\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Oda\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for billingCodesGet
     *
     * .
     *
     */
    public function testBillingCodesGet()
    {
    }

    /**
     * Test case for callbacksIdDetailsGet
     *
     * .
     *
     */
    public function testCallbacksIdDetailsGet()
    {
    }

    /**
     * Test case for candidatesGet
     *
     * .
     *
     */
    public function testCandidatesGet()
    {
    }

    /**
     * Test case for candidatesIdDocumentsGet
     *
     * .
     *
     */
    public function testCandidatesIdDocumentsGet()
    {
    }

    /**
     * Test case for candidatesIdDocumentsPost
     *
     * .
     *
     */
    public function testCandidatesIdDocumentsPost()
    {
    }

    /**
     * Test case for candidatesIdGet
     *
     * .
     *
     */
    public function testCandidatesIdGet()
    {
    }

    /**
     * Test case for candidatesIdPut
     *
     * .
     *
     */
    public function testCandidatesIdPut()
    {
    }

    /**
     * Test case for candidatesIdTrustPost
     *
     * .
     *
     */
    public function testCandidatesIdTrustPost()
    {
    }

    /**
     * Test case for candidatesPost
     *
     * .
     *
     */
    public function testCandidatesPost()
    {
    }

    /**
     * Test case for healthGet
     *
     * .
     *
     */
    public function testHealthGet()
    {
    }

    /**
     * Test case for identitiesIdGet
     *
     * .
     *
     */
    public function testIdentitiesIdGet()
    {
    }

    /**
     * Test case for identitiesIdRetryPost
     *
     * .
     *
     */
    public function testIdentitiesIdRetryPost()
    {
    }

    /**
     * Test case for identitiesIdVerificationPut
     *
     * .
     *
     */
    public function testIdentitiesIdVerificationPut()
    {
    }

    /**
     * Test case for identitiesPost
     *
     * .
     *
     */
    public function testIdentitiesPost()
    {
    }

    /**
     * Test case for packagesGet
     *
     * .
     *
     */
    public function testPackagesGet()
    {
    }

    /**
     * Test case for packagesIdPriceGet
     *
     * .
     *
     */
    public function testPackagesIdPriceGet()
    {
    }

    /**
     * Test case for referenceCodesGet
     *
     * .
     *
     */
    public function testReferenceCodesGet()
    {
    }

    /**
     * Test case for screeningsGet
     *
     * .
     *
     */
    public function testScreeningsGet()
    {
    }

    /**
     * Test case for screeningsIdAdverseActionsPost
     *
     * .
     *
     */
    public function testScreeningsIdAdverseActionsPost()
    {
    }

    /**
     * Test case for screeningsIdDocumentsPost
     *
     * .
     *
     */
    public function testScreeningsIdDocumentsPost()
    {
    }

    /**
     * Test case for screeningsIdGet
     *
     * .
     *
     */
    public function testScreeningsIdGet()
    {
    }

    /**
     * Test case for screeningsIdInvitePost
     *
     * .
     *
     */
    public function testScreeningsIdInvitePost()
    {
    }

    /**
     * Test case for screeningsIdReportGet
     *
     * .
     *
     */
    public function testScreeningsIdReportGet()
    {
    }

    /**
     * Test case for screeningsIdReportLinksPost
     *
     * .
     *
     */
    public function testScreeningsIdReportLinksPost()
    {
    }

    /**
     * Test case for screeningsIdReportPdfGet
     *
     * .
     *
     */
    public function testScreeningsIdReportPdfGet()
    {
    }

    /**
     * Test case for screeningsPost
     *
     * .
     *
     */
    public function testScreeningsPost()
    {
    }

    /**
     * Test case for subscriptionsIdDelete
     *
     * .
     *
     */
    public function testSubscriptionsIdDelete()
    {
    }

    /**
     * Test case for subscriptionsIdEventsGet
     *
     * .
     *
     */
    public function testSubscriptionsIdEventsGet()
    {
    }

    /**
     * Test case for subscriptionsIdGet
     *
     * .
     *
     */
    public function testSubscriptionsIdGet()
    {
    }

    /**
     * Test case for subscriptionsIdJobPost
     *
     * .
     *
     */
    public function testSubscriptionsIdJobPost()
    {
    }

    /**
     * Test case for subscriptionsPost
     *
     * .
     *
     */
    public function testSubscriptionsPost()
    {
    }

    /**
     * Test case for trustedUsersIdGet
     *
     * .
     *
     */
    public function testTrustedUsersIdGet()
    {
    }

    /**
     * Test case for trustedUsersPost
     *
     * .
     *
     */
    public function testTrustedUsersPost()
    {
    }

    /**
     * Test case for trustsIdDelete
     *
     * .
     *
     */
    public function testTrustsIdDelete()
    {
    }
}
